ADD application level authentication (with Cognito)
NASA-PDS/doi-ui pull request #164
Opened 2022-09-01 21:14 UTC by ramesh-maddegoda

## 🗒️ Summary
Added application level authentication (with Cognito) to implement OAuth2 Authorization Code Grant with PKCE (Proof Key for Code Exchange) using react-oauth2-pkce library. 
Updated error messages to show relevant connectivity/auth related messages

## ♻️ Related Issues
Refer to the issue: NASA-PDS/doi-ui#159

2022-09-01 21:28 UTC, jordanpadams requested changes

2022-09-01 21:28 UTC, jordanpadams commented on src/AuthenticationWrapper.js
> +            <h4>Authenticating...</h4>
@ramesh-maddegoda this one appears to still be associated with the latest code base. is this relevant still?

2022-09-01 23:26 UTC, ramesh-maddegoda commented on src/AuthenticationWrapper.js
> +            <h4>Authenticating...</h4>
@jordanpadams , I fixed the earlier error, where I did not use brackets after return and did not have a semi colon. After fixing it, it seems now sonartype think it as a regular expression. In this case it is allowed to have HTML defined in the  JavaScript. However, it seems sonar did not expect to see HTML here and analyzes it as a regular expression in JavaScript.

2022-09-02 21:11 UTC, jordanpadams commented on src/AuthenticationWrapper.js
> +            <h4>Authenticating...</h4>
@ramesh-maddegoda copy. that is fine. feel free to use the sonatype commands in the future to close these out

2022-09-02 21:12 UTC, jordanpadams commented on src/AuthenticationWrapper.js
> +            <h4>Authenticating...</h4>
@sonatype-lift ignore

2022-09-02 21:12 UTC, jordanpadams commented on src/AuthenticationWrapper.js
> +            <h4>Authenticating...</h4>
@sonatype-lift ignore

2022-09-02 21:12 UTC, jordanpadams commented on package.json
> +    "styled-components": "^5.3.5",
@sonatype-lift ignore

awaiting dependency upgrade to fix

2022-09-02 21:12 UTC, jordanpadams approved these changes

2022-09-02 21:13 UTC, merged

2022-09-06 20:15 UTC, ramesh-maddegoda commented
Merged changes